-- colors/colorscheme.lua

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#EDEDED", bg = "#212121"},
TabLineSel = {link = "Normal"},
Added = {fg = "#CDF297"},
Boolean = {fg = "#F2979B"},
BufferLineOffset = {fg = "#EDEDED", bg = "#171717"},
Changed = {fg = "#97B4F2"},
Character = {fg = "#97D8F2"},
ColorColumn = {bg = "#4A4A4A"},
Comment = {fg = "#9C9C9C", italic = true},
["@comment"] = {link = "Comment"},
["@comment.documentation"] = {link = "Comment"},
["@string.documentation"] = {link = "Comment"},
Conceal = {fg = "#878787"},
Conditional = {fg = "#97D8F2"},
Constant = {fg = "#EDEDED"},
CurSearch = {fg = "#171717", bg = "#F2979B"},
Cursor = {fg = "#212121", bg = "#EDEDED"},
CursorColumn = {bg = "#2E2E2E"},
CursorIM = {fg = "#212121", bg = "#EDEDED"},
CursorLine = {bg = "#2E2E2E"},
CursorLineNr = {fg = "#B8B8B8"},
Debug = {fg = "#F2D297"},
Define = {fg = "#97D8F2"},
Delimiter = {fg = "#97D8F2"},
DiagnosticError = {fg = "#F2979B"},
DiagnosticFloatingError = {fg = "#F2979B"},
DiagnosticFloatingHint = {fg = "#97D8F2"},
DiagnosticFloatingInfo = {fg = "#97B4F2"},
DiagnosticFloatingOk = {fg = "#CDF297"},
DiagnosticFloatingWarn = {fg = "#F2D297"},
DiagnosticHint = {fg = "#97D8F2"},
DiagnosticInfo = {fg = "#97B4F2"},
DiagnosticOk = {fg = "#CDF297"},
DiagnosticSignError = {fg = "#F2979B"},
DiagnosticSignHint = {fg = "#97D8F2"},
DiagnosticSignInfo = {fg = "#97B4F2"},
DiagnosticSignOk = {fg = "#CDF297"},
DiagnosticSignWarn = {fg = "#F2D297"},
DiagnosticUnderlineError = {sp = "#F2979B", underline = true},
DiagnosticUnderlineHint = {sp = "#97D8F2", underline = true},
DiagnosticUnderlineInfo = {sp = "#97B4F2", underline = true},
DiagnosticUnderlineOk = {sp = "#CDF297", underline = true},
DiagnosticUnderlineWarn = {sp = "#F2D297", underline = true},
DiagnosticVirtualTextError = {fg = "#F2979B", bg = "#352C2D"},
DiagnosticVirtualTextHint = {fg = "#97D8F2", bg = "#2C3235"},
DiagnosticVirtualTextInfo = {fg = "#97B4F2", bg = "#2C2F35"},
DiagnosticVirtualTextOk = {fg = "#CDF297", bg = "#31352C"},
DiagnosticVirtualTextWarn = {fg = "#F2D297", bg = "#352C2D"},
DiagnosticWarn = {fg = "#F2D297"},
DiffAdd = {bg = "#31352C"},
DiffChange = {bg = "#2C2F35"},
DiffDelete = {bg = "#352C2D"},
DiffText = {bg = "#2C3235"},
Directory = {fg = "#B8B8B8"},
EndOfBuffer = {fg = "#212121"},
Error = {fg = "#F2979B", bg = "#352C2D"},
ErrorMsg = {fg = "#F2979B", bold = true, italic = true},
Exception = {fg = "#F2979B"},
Float = {fg = "#F2979B"},
FloatBorder = {fg = "#737373", bg = "#171717"},
FzfLuaBorder = {link = "FloatBorder"},
FoldColumn = {fg = "#4A4A4A"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#9C9C9C", bg = "#2E2E2E"},
Function = {fg = "#97D8F2"},
FzfLuaBufFlagAlt = {fg = "#97D8F2"},
FzfLuaBufFlagCur = {fg = "#F2979B"},
FzfLuaBufName = {fg = "#CD97F2"},
FzfLuaBufNr = {fg = "#F2D297"},
FzfLuaHeaderBind = {fg = "#F2D297"},
FzfLuaHeaderText = {fg = "#F2979B"},
FzfLuaLiveSym = {fg = "#F2979B"},
FzfLuaPathColNr = {fg = "#97D8F2"},
FzfLuaPathLineNr = {fg = "#CDF297"},
FzfLuaTabMarker = {fg = "#F2D297"},
FzfLuaTabTitle = {fg = "#97B4F2"},
Identifier = {fg = "#97D8F2"},
IncSearch = {fg = "#171717", bg = "#F2D297"},
Include = {fg = "#97D8F2"},
Keyword = {fg = "#CD97F2"},
Label = {fg = "#97D8F2"},
LineNr = {fg = "#5C5C5C"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspCodeLens = {fg = "#5C5C5C"},
LspCodeLensSeparator = {link = "LspCodeLens"},
LspReferenceRead = {bg = "#383838"},
LspReferenceText = {bg = "#383838"},
LspReferenceWrite = {bg = "#383838"},
LspSignatureActiveParameter = {bg = "#2E2E2E", bold = true},
Macro = {fg = "#97B4F2"},
MatchParen = {fg = "#212121", bg = "#97B4F2"},
ModeMsg = {fg = "#B8B8B8", bold = true},
MoreMsg = {fg = "#97B4F2"},
MsgArea = {},
MsgSeparator = {},
Noise = {fg = "#97D8F2"},
NonText = {fg = "#383838"},
SpecialKey = {link = "NonText"},
NormalFloat = {fg = "#B8B8B8", bg = "#171717"},
FzfLuaNormal = {link = "NormalFloat"},
FzfLuaPreviewNormal = {link = "NormalFloat"},
NvimTreeNormal = {link = "NormalFloat"},
NormalNC = {fg = "#EDEDED", bg = "#212121"},
Number = {fg = "#F2979B"},
NvimTreeCursorLine = {fg = "#97B4F2", bg = "#2C2F35"},
NvimTreeRootFolder = {fg = "#B8B8B8", bold = true},
NvimTreeWinSeparator = {fg = "#171717", bg = "#171717"},
BufferlineOffsetSeparator = {link = "NvimTreeWinSeparator"},
Operator = {fg = "#97D8F2"},
Pmenu = {fg = "#B8B8B8", bg = "#171717"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#171717"},
PmenuSel = {fg = "#97B4F2", bg = "#2C2F35"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#383838"},
PreCondit = {fg = "#97B4F2"},
PreProc = {fg = "#CD97F2"},
Question = {fg = "#97B4F2"},
QuickFixLine = {bg = "#4A4A4A"},
Removed = {fg = "#F2979B"},
Repeat = {fg = "#97D8F2"},
Search = {fg = "#171717", bg = "#97B4F2"},
SignColumn = {fg = "#4A4A4A"},
CursorLineSign = {link = "SignColumn"},
SnacksDashboardDesc = {fg = "#CD97F2"},
SnacksDashboardFooter = {fg = "#F2D297"},
SnacksDashboardHeader = {fg = "#EDEDED"},
SnacksDashboardIcon = {fg = "#F2979B"},
SnacksDashboardKey = {fg = "#97B4F2"},
SnacksDashboardSpecial = {fg = "#F2D297"},
SnacksIndentScope = {fg = "#5C5C5C"},
Special = {fg = "#97D8F2"},
SpecialChar = {fg = "#F2979B"},
SpecialComment = {fg = "#9C9C9C", italic = true},
SpellBad = {sp = "#F2979B", undercurl = true},
SpellCap = {sp = "#F2D297", undercurl = true},
SpellLocal = {sp = "#97B4F2", undercurl = true},
SpellRare = {sp = "#CDF297", undercurl = true},
Statement = {fg = "#F2979B"},
StatusLine = {fg = "#B8B8B8", bg = "#171717"},
StatusLineNC = {fg = "#4A4A4A", bg = "#171717"},
StorageClass = {fg = "#B6CAD2"},
String = {fg = "#CDF297"},
Structure = {fg = "#97D8F2"},
Substitute = {fg = "#F2979B", bg = "#4A4A4A"},
TabLine = {fg = "#4A4A4A", bg = "#171717"},
TabLineFill = {bg = "#171717"},
Tag = {fg = "#F2979B"},
TermCursor = {fg = "#212121", bg = "#B8B8B8"},
TermCursorNC = {fg = "#212121", bg = "#9C9C9C"},
Title = {fg = "#EDEDED"},
FloatTitle = {link = "Title"},
Todo = {fg = "#97D8F2"},
Type = {fg = "#CD97F2"},
Typedef = {fg = "#F2979B"},
Underlined = {underline = true},
["@markup.underline"] = {link = "Underlined"},
VertSplit = {fg = "#737373"},
Visual = {bg = "#383838"},
VisualNOS = {bg = "#4A4A4A"},
WarningMsg = {fg = "#F2D297"},
Whitespace = {fg = "#4A4A4A"},
WildMenu = {bg = "#4A4A4A"},
WinBar = {fg = "#B8B8B8"},
WinBarNC = {fg = "#5C5C5C"},
Winseparator = {fg = "#737373"},
lCursor = {fg = "#212121", bg = "#EDEDED"},
["@attribute"] = {fg = "#CD97F2"},
["@attribute.builtin"] = {fg = "#F2D297"},
["@boolean"] = {fg = "#F2979B"},
["@character"] = {fg = "#EDEDED"},
["@character.special"] = {fg = "#F2979B"},
["@comment.error"] = {fg = "#F2979B"},
["@comment.note"] = {fg = "#97D8F2"},
["@comment.todo"] = {fg = "#97B4F2"},
["@comment.warning"] = {fg = "#F2D297"},
["@constant"] = {fg = "#EDEDED"},
["@constant.builtin"] = {fg = "#97D8F2"},
["@constant.macro"] = {fg = "#97B4F2"},
["@constructor"] = {fg = "#CD97F2"},
["@diff.delta"] = {fg = "#97B4F2"},
["@diff.minus"] = {fg = "#F2979B"},
["@diff.plus"] = {fg = "#CDF297"},
["@function"] = {fg = "#97B4F2"},
["@function.builtin"] = {fg = "#97B4F2"},
["@function.call"] = {fg = "#97B4F2"},
["@function.macro"] = {fg = "#97B4F2"},
["@function.method"] = {fg = "#97B4F2"},
["@function.method.call"] = {fg = "#97B4F2"},
["@keyword"] = {fg = "#CD97F2"},
["@keyword.conditional"] = {fg = "#97D8F2", italic = true},
["@keyword.conditional.ternary"] = {fg = "#97D8F2"},
["@keyword.coroutine"] = {fg = "#CD97F2"},
["@keyword.debug"] = {fg = "#F2D297", italic = true},
["@keyword.directive"] = {fg = "#97D8F2", italic = true},
["@keyword.directive.define"] = {fg = "#97D8F2", italic = true},
["@keyword.exception"] = {fg = "#97D8F2", italic = true},
["@keyword.function"] = {fg = "#F2979B"},
["@keyword.import"] = {fg = "#97D8F2"},
["@keyword.modifier"] = {fg = "#CD97F2"},
["@keyword.operator"] = {fg = "#97D8F2"},
["@keyword.repeat"] = {fg = "#97D8F2", italic = true},
["@keyword.return"] = {fg = "#97D8F2", italic = true},
["@keyword.type"] = {fg = "#CD97F2"},
["@label"] = {fg = "#F2D297"},
["@label.markdown"] = {fg = "#CDF297"},
["@lsp.type.class.markdown"] = {fg = "#CDF297"},
["@markup.heading"] = {fg = "#EDEDED"},
["@markup.heading.1"] = {fg = "#EDEDED"},
["@markup.heading.1.markdown"] = {fg = "#F2D297"},
["@markup.heading.2"] = {fg = "#EDEDED"},
["@markup.heading.2.markdown"] = {fg = "#F2D297"},
["@markup.heading.3"] = {fg = "#EDEDED"},
["@markup.heading.3.markdown"] = {fg = "#F2D297"},
["@markup.heading.4"] = {fg = "#EDEDED"},
["@markup.heading.4.markdown"] = {fg = "#F2D297"},
["@markup.heading.5"] = {fg = "#EDEDED"},
["@markup.heading.5.markdown"] = {fg = "#F2D297"},
["@markup.heading.6"] = {fg = "#EDEDED"},
["@markup.heading.6.markdown"] = {fg = "#F2D297"},
["@markup.heading.markdown"] = {fg = "#F2D297"},
["@markup.italic"] = {fg = "#F2979B", italic = true},
["@markup.link"] = {fg = "#97D8F2"},
["@markup.link.label"] = {fg = "#CDF297"},
["@markup.link.url"] = {fg = "#F2979B"},
["@markup.list"] = {fg = "#97D8F2"},
["@markup.list.checked"] = {fg = "#CDF297"},
["@markup.list.unchecked"] = {fg = "#97B4F2"},
["@markup.math"] = {fg = "#97B4F2"},
["@markup.quote"] = {fg = "#97D8F2", italic = true},
["@markup.raw"] = {fg = "#EDEDED"},
["@markup.raw.block"] = {fg = "#B8B8B8"},
["@markup.raw.markdown_inline"] = {fg = "#CDF297"},
["@markup.strikethrough"] = {fg = "#EDEDED", strikethrough = true},
["@markup.strong"] = {fg = "#F2979B", bold = true},
["@module"] = {fg = "#F2D297"},
["@number"] = {fg = "#F2979B"},
["@number.float"] = {fg = "#F2979B"},
["@operator"] = {fg = "#97D8F2"},
["@property"] = {fg = "#B6CAD2"},
["@punctuation.bracket"] = {fg = "#97D8F2"},
["@punctuation.delimiter"] = {fg = "#97D8F2"},
["@punctuation.special"] = {fg = "#97D8F2"},
["@string"] = {fg = "#CDF297"},
["@string.escape"] = {fg = "#EDEDED"},
["@string.regexp"] = {fg = "#CDF297"},
["@string.special.symbol"] = {fg = "#97D8F2"},
["@string.special.url"] = {underline = true},
["@tag"] = {fg = "#F2979B"},
["@tag.attribute"] = {fg = "#CD97F2"},
["@tag.delimiter"] = {fg = "#97D8F2"},
["@type"] = {fg = "#F2D297"},
["@type.builtin"] = {fg = "#F2D297"},
["@type.definition"] = {fg = "#F2D297"},
["@variable"] = {fg = "#EDEDED"},
["@variable.builtin"] = {fg = "#97D8F2"},
["@variable.member"] = {fg = "#EDEDED"},
["@variable.parameter"] = {fg = "#EDEDED", italic = true},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='neutr'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
