-- colors/neutr.lua

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#EBEBEB", bg = "#1F1F1F"},
TabLineSel = {link = "Normal"},
Added = {fg = "#C4F297"},
Boolean = {fg = "#F29797"},
BufferLineOffset = {fg = "#EBEBEB", bg = "#141414"},
Changed = {fg = "#97ADF2"},
Character = {fg = "#97F2F2"},
ColorColumn = {bg = "#474747"},
Comment = {fg = "#999999", italic = true},
["@comment"] = {link = "Comment"},
["@comment.documentation"] = {link = "Comment"},
["@string.documentation"] = {link = "Comment"},
Conceal = {fg = "#878787"},
Conditional = {fg = "#97F2F2"},
Constant = {fg = "#EBEBEB"},
CurSearch = {fg = "#141414", bg = "#F29797"},
Cursor = {fg = "#1F1F1F", bg = "#EBEBEB"},
CursorColumn = {bg = "#2B2B2B"},
CursorIM = {fg = "#1F1F1F", bg = "#EBEBEB"},
CursorLine = {bg = "#2B2B2B"},
CursorLineNr = {fg = "#C2C2C2"},
Debug = {fg = "#F2DB97"},
Define = {fg = "#97F2F2"},
Delimiter = {fg = "#97F2F2"},
DiagnosticError = {fg = "#F29797"},
DiagnosticFloatingError = {fg = "#F29797"},
DiagnosticFloatingHint = {fg = "#97F2F2"},
DiagnosticFloatingInfo = {fg = "#97ADF2"},
DiagnosticFloatingOk = {fg = "#C4F297"},
DiagnosticFloatingWarn = {fg = "#F2DB97"},
DiagnosticHint = {fg = "#97F2F2"},
DiagnosticInfo = {fg = "#97ADF2"},
DiagnosticOk = {fg = "#C4F297"},
DiagnosticSignError = {fg = "#F29797"},
DiagnosticSignHint = {fg = "#97F2F2"},
DiagnosticSignInfo = {fg = "#97ADF2"},
DiagnosticSignOk = {fg = "#C4F297"},
DiagnosticSignWarn = {fg = "#F2DB97"},
DiagnosticUnderlineError = {sp = "#F29797", underline = true},
DiagnosticUnderlineHint = {sp = "#97F2F2", underline = true},
DiagnosticUnderlineInfo = {sp = "#97ADF2", underline = true},
DiagnosticUnderlineOk = {sp = "#C4F297", underline = true},
DiagnosticUnderlineWarn = {sp = "#F2DB97", underline = true},
DiagnosticVirtualTextError = {fg = "#F29797", bg = "#352C2C"},
DiagnosticVirtualTextHint = {fg = "#97F2F2", bg = "#2C3535"},
DiagnosticVirtualTextInfo = {fg = "#97ADF2", bg = "#2C2E35"},
DiagnosticVirtualTextOk = {fg = "#C4F297", bg = "#30352C"},
DiagnosticVirtualTextWarn = {fg = "#F2DB97", bg = "#35332C"},
DiagnosticWarn = {fg = "#F2DB97"},
DiffAdd = {bg = "#30352C"},
DiffChange = {bg = "#2C2E35"},
DiffDelete = {bg = "#352C2C"},
DiffText = {bg = "#2C3535"},
Directory = {fg = "#C2C2C2"},
EndOfBuffer = {fg = "#1F1F1F"},
Error = {fg = "#F29797", bg = "#352C2C"},
ErrorMsg = {fg = "#F29797", bold = true, italic = true},
Exception = {fg = "#F29797"},
Float = {fg = "#F29797"},
FloatBorder = {fg = "#707070", bg = "#141414"},
FzfLuaBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#EBEBEB", bg = "#141414"},
FoldColumn = {fg = "#474747"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#999999", bg = "#2B2B2B"},
Function = {fg = "#97F2F2"},
FzfLuaBufFlagAlt = {fg = "#97F2F2"},
FzfLuaBufFlagCur = {fg = "#F29797"},
FzfLuaBufName = {fg = "#C497F2"},
FzfLuaBufNr = {fg = "#F2DB97"},
FzfLuaHeaderBind = {fg = "#F2DB97"},
FzfLuaHeaderText = {fg = "#F29797"},
FzfLuaLiveSym = {fg = "#F29797"},
FzfLuaPathColNr = {fg = "#97F2F2"},
FzfLuaPathLineNr = {fg = "#C4F297"},
FzfLuaTabMarker = {fg = "#F2DB97"},
FzfLuaTabTitle = {fg = "#97ADF2"},
Identifier = {fg = "#97F2F2"},
IncSearch = {fg = "#141414", bg = "#F2DB97"},
Include = {fg = "#97F2F2"},
Keyword = {fg = "#C497F2"},
Label = {fg = "#97F2F2"},
LineNr = {fg = "#5C5C5C"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspCodeLens = {fg = "#5C5C5C"},
LspCodeLensSeparator = {link = "LspCodeLens"},
LspReferenceRead = {bg = "#383838"},
LspReferenceText = {bg = "#383838"},
LspReferenceWrite = {bg = "#383838"},
LspSignatureActiveParameter = {bg = "#2B2B2B", bold = true},
Macro = {fg = "#97ADF2"},
MatchParen = {fg = "#F2DB97", bg = "#383838"},
ModeMsg = {fg = "#C2C2C2", bold = true},
MoreMsg = {fg = "#97ADF2"},
MsgArea = {},
MsgSeparator = {},
NeoTreeCursorLine = {fg = "#97ADF2", bg = "#2C2E35"},
NeoTreeNormal = {fg = "#C2C2C2", bg = "#141414"},
NeoTreeRootName = {fg = "#C2C2C2", bold = true},
NeoTreeWinSeparator = {fg = "#141414", bg = "#141414"},
Noise = {fg = "#97F2F2"},
NonText = {fg = "#383838"},
SpecialKey = {link = "NonText"},
NormalFloat = {fg = "#C2C2C2", bg = "#141414"},
FzfLuaNormal = {link = "NormalFloat"},
FzfLuaPreviewNormal = {link = "NormalFloat"},
NormalNC = {fg = "#EBEBEB", bg = "#1F1F1F"},
Number = {fg = "#F29797"},
NvimTreeCursorLine = {fg = "#97ADF2", bg = "#2C2E35"},
NvimTreeNormal = {fg = "#C2C2C2", bg = "#141414"},
NvimTreeRootFolder = {fg = "#C2C2C2", bold = true},
NvimTreeWinSeparator = {fg = "#141414", bg = "#141414"},
BufferlineOffsetSeparator = {link = "NvimTreeWinSeparator"},
Operator = {fg = "#97F2F2"},
Pmenu = {fg = "#C2C2C2", bg = "#141414"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#141414"},
PmenuSel = {fg = "#97ADF2", bg = "#2C2E35"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#383838"},
PreCondit = {fg = "#97ADF2"},
PreProc = {fg = "#C497F2"},
Question = {fg = "#97ADF2"},
QuickFixLine = {bg = "#474747"},
Removed = {fg = "#F29797"},
Repeat = {fg = "#97F2F2"},
Search = {fg = "#141414", bg = "#97ADF2"},
SignColumn = {fg = "#474747"},
CursorLineSign = {link = "SignColumn"},
SnacksDashboardDesc = {fg = "#C497F2"},
SnacksDashboardFooter = {fg = "#F2DB97"},
SnacksDashboardHeader = {fg = "#EBEBEB"},
SnacksDashboardIcon = {fg = "#F29797"},
SnacksDashboardKey = {fg = "#97ADF2"},
SnacksDashboardSpecial = {fg = "#F2DB97"},
SnacksIndentScope = {fg = "#5C5C5C"},
SnacksPickerBufFlags = {fg = "#878787"},
SnacksPickerDir = {fg = "#878787"},
SnacksPickerKeymapRhs = {fg = "#878787"},
SnacksPickerTotals = {fg = "#878787"},
Special = {fg = "#97F2F2"},
SpecialChar = {fg = "#F29797"},
SpecialComment = {fg = "#999999", italic = true},
SpellBad = {sp = "#F29797", undercurl = true},
SpellCap = {sp = "#F2DB97", undercurl = true},
SpellLocal = {sp = "#97ADF2", undercurl = true},
SpellRare = {sp = "#C4F297", undercurl = true},
Statement = {fg = "#F29797"},
StatusLine = {fg = "#C2C2C2", bg = "#1F1F1F"},
StatusLineNC = {fg = "#474747", bg = "#1F1F1F"},
StorageClass = {fg = "#B6D2D2"},
String = {fg = "#C4F297"},
Structure = {fg = "#97F2F2"},
Substitute = {fg = "#F29797", bg = "#474747"},
TabLine = {fg = "#474747", bg = "#141414"},
TabLineFill = {bg = "#141414"},
Tag = {fg = "#F29797"},
TermCursor = {fg = "#1F1F1F", bg = "#C2C2C2"},
TermCursorNC = {fg = "#1F1F1F", bg = "#999999"},
Title = {fg = "#EBEBEB"},
Todo = {fg = "#97F2F2"},
Type = {fg = "#C497F2"},
Typedef = {fg = "#F29797"},
Underlined = {underline = true},
["@markup.underline"] = {link = "Underlined"},
VertSplit = {fg = "#707070"},
Visual = {bg = "#383838"},
VisualNOS = {bg = "#474747"},
WarningMsg = {fg = "#F2DB97"},
Whitespace = {fg = "#383838"},
WildMenu = {bg = "#474747"},
WinBar = {fg = "#C2C2C2"},
WinBarNC = {fg = "#5C5C5C"},
Winseparator = {fg = "#707070"},
lCursor = {fg = "#1F1F1F", bg = "#EBEBEB"},
["@attribute"] = {fg = "#C497F2"},
["@attribute.builtin"] = {fg = "#F2DB97"},
["@boolean"] = {fg = "#F29797"},
["@character"] = {fg = "#EBEBEB"},
["@character.special"] = {fg = "#F29797"},
["@comment.error"] = {fg = "#F29797"},
["@comment.note"] = {fg = "#97F2F2"},
["@comment.todo"] = {fg = "#97ADF2"},
["@comment.warning"] = {fg = "#F2DB97"},
["@constant"] = {fg = "#EBEBEB"},
["@constant.builtin"] = {fg = "#97F2F2"},
["@constant.macro"] = {fg = "#97ADF2"},
["@constructor"] = {fg = "#C497F2"},
["@diff.delta"] = {fg = "#97ADF2"},
["@diff.minus"] = {fg = "#F29797"},
["@diff.plus"] = {fg = "#C4F297"},
["@function"] = {fg = "#97ADF2"},
["@function.builtin"] = {fg = "#97ADF2"},
["@function.call"] = {fg = "#97ADF2"},
["@function.macro"] = {fg = "#97ADF2"},
["@function.method"] = {fg = "#97ADF2"},
["@function.method.call"] = {fg = "#97ADF2"},
["@keyword"] = {fg = "#C497F2"},
["@keyword.c"] = {fg = "#F29797"},
["@keyword.conditional"] = {fg = "#97F2F2", italic = true},
["@keyword.conditional.ternary"] = {fg = "#97F2F2"},
["@keyword.coroutine"] = {fg = "#C497F2"},
["@keyword.cpp"] = {fg = "#F29797"},
["@keyword.debug"] = {fg = "#F2DB97", italic = true},
["@keyword.directive"] = {fg = "#97F2F2", italic = true},
["@keyword.directive.define"] = {fg = "#97F2F2", italic = true},
["@keyword.exception"] = {fg = "#97F2F2", italic = true},
["@keyword.function"] = {fg = "#C497F2"},
["@keyword.function.rust"] = {fg = "#F29797"},
["@keyword.import"] = {fg = "#97F2F2"},
["@keyword.modifier"] = {fg = "#C497F2"},
["@keyword.operator"] = {fg = "#97F2F2"},
["@keyword.repeat"] = {fg = "#97F2F2", italic = true},
["@keyword.return"] = {fg = "#97F2F2", italic = true},
["@keyword.type"] = {fg = "#C497F2"},
["@label"] = {fg = "#F2DB97"},
["@label.markdown"] = {fg = "#C4F297"},
["@lsp.type.class.markdown"] = {fg = "#C4F297"},
["@markup.heading"] = {fg = "#EBEBEB"},
["@markup.heading.1"] = {fg = "#EBEBEB"},
["@markup.heading.1.markdown"] = {fg = "#F2DB97"},
["@markup.heading.2"] = {fg = "#EBEBEB"},
["@markup.heading.2.markdown"] = {fg = "#F2DB97"},
["@markup.heading.3"] = {fg = "#EBEBEB"},
["@markup.heading.3.markdown"] = {fg = "#F2DB97"},
["@markup.heading.4"] = {fg = "#EBEBEB"},
["@markup.heading.4.markdown"] = {fg = "#F2DB97"},
["@markup.heading.5"] = {fg = "#EBEBEB"},
["@markup.heading.5.markdown"] = {fg = "#F2DB97"},
["@markup.heading.6"] = {fg = "#EBEBEB"},
["@markup.heading.6.markdown"] = {fg = "#F2DB97"},
["@markup.heading.markdown"] = {fg = "#F2DB97"},
["@markup.italic"] = {fg = "#F29797", italic = true},
["@markup.link"] = {fg = "#97F2F2"},
["@markup.link.label"] = {fg = "#C4F297"},
["@markup.link.url"] = {fg = "#F29797"},
["@markup.list"] = {fg = "#97F2F2"},
["@markup.list.checked"] = {fg = "#C4F297"},
["@markup.list.unchecked"] = {fg = "#97ADF2"},
["@markup.math"] = {fg = "#97ADF2"},
["@markup.quote"] = {fg = "#97F2F2", italic = true},
["@markup.raw"] = {fg = "#EBEBEB"},
["@markup.raw.block"] = {fg = "#C2C2C2"},
["@markup.raw.markdown_inline"] = {fg = "#C4F297"},
["@markup.strikethrough"] = {fg = "#EBEBEB", strikethrough = true},
["@markup.strong"] = {fg = "#F29797", bold = true},
["@module"] = {fg = "#F2DB97"},
["@module.python"] = {fg = "#EBEBEB"},
["@number"] = {fg = "#F29797"},
["@number.float"] = {fg = "#F29797"},
["@operator"] = {fg = "#97F2F2"},
["@property"] = {fg = "#B6D2D2"},
["@punctuation.bracket"] = {fg = "#97F2F2"},
["@punctuation.delimiter"] = {fg = "#97F2F2"},
["@punctuation.special"] = {fg = "#97F2F2"},
["@string"] = {fg = "#C4F297"},
["@string.escape"] = {fg = "#EBEBEB"},
["@string.regexp"] = {fg = "#C4F297"},
["@string.special.symbol"] = {fg = "#97F2F2"},
["@string.special.url"] = {underline = true},
["@tag"] = {fg = "#F29797"},
["@tag.attribute"] = {fg = "#C497F2"},
["@tag.delimiter"] = {fg = "#97F2F2"},
["@type"] = {fg = "#F2DB97"},
["@type.builtin"] = {fg = "#F2DB97"},
["@type.builtin.c"] = {fg = "#C497F2"},
["@type.builtin.cpp"] = {fg = "#C497F2"},
["@type.definition"] = {fg = "#F2DB97"},
["@variable"] = {fg = "#EBEBEB"},
["@variable.builtin"] = {fg = "#97F2F2"},
["@variable.member"] = {fg = "#EBEBEB"},
["@variable.parameter"] = {fg = "#EBEBEB", italic = true},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='neutr'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
