-- colors/neutr.lua

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#EBEBEB", bg = "#1E1E1E"},
TabLineSel = {link = "Normal"},
Added = {fg = "#CDF297"},
Boolean = {fg = "#F2979C"},
BufferLineFill = {bg = "#1E1E1E"},
BufferLineOffset = {fg = "#EBEBEB", bg = "#131313"},
Changed = {fg = "#97B4F2"},
Character = {fg = "#97D8F2"},
ColorColumn = {bg = "#484848"},
Comment = {fg = "#999999", italic = true},
["@comment"] = {link = "Comment"},
["@comment.documentation"] = {link = "Comment"},
["@string.documentation"] = {link = "Comment"},
Conceal = {fg = "#868686"},
Conditional = {fg = "#97D8F2"},
Constant = {fg = "#EBEBEB"},
CurSearch = {fg = "#131313", bg = "#F2979C"},
Cursor = {fg = "#1E1E1E", bg = "#EBEBEB"},
CursorColumn = {bg = "#2C2C2C"},
CursorIM = {fg = "#1E1E1E", bg = "#EBEBEB"},
CursorLine = {bg = "#2C2C2C"},
CursorLineNr = {fg = "#C1C1C1"},
Debug = {fg = "#F2D297"},
Define = {fg = "#97D8F2"},
Delimiter = {fg = "#97D8F2"},
DiagnosticError = {fg = "#F2979C"},
DiagnosticFloatingError = {fg = "#F2979C"},
DiagnosticFloatingHint = {fg = "#97D8F2"},
DiagnosticFloatingInfo = {fg = "#97B4F2"},
DiagnosticFloatingOk = {fg = "#CDF297"},
DiagnosticFloatingWarn = {fg = "#F2D297"},
DiagnosticHint = {fg = "#97D8F2"},
DiagnosticInfo = {fg = "#97B4F2"},
DiagnosticOk = {fg = "#CDF297"},
DiagnosticSignError = {fg = "#F2979C"},
DiagnosticSignHint = {fg = "#97D8F2"},
DiagnosticSignInfo = {fg = "#97B4F2"},
DiagnosticSignOk = {fg = "#CDF297"},
DiagnosticSignWarn = {fg = "#F2D297"},
DiagnosticUnderlineError = {sp = "#F2979C", underline = true},
DiagnosticUnderlineHint = {sp = "#97D8F2", underline = true},
DiagnosticUnderlineInfo = {sp = "#97B4F2", underline = true},
DiagnosticUnderlineOk = {sp = "#CDF297", underline = true},
DiagnosticUnderlineWarn = {sp = "#F2D297", underline = true},
DiagnosticVirtualTextError = {fg = "#F2979C", bg = "#352C2D"},
DiagnosticVirtualTextHint = {fg = "#97D8F2", bg = "#2C3235"},
DiagnosticVirtualTextInfo = {fg = "#97B4F2", bg = "#2C2F35"},
DiagnosticVirtualTextOk = {fg = "#CDF297", bg = "#31352C"},
DiagnosticVirtualTextWarn = {fg = "#F2D297", bg = "#35322C"},
DiagnosticWarn = {fg = "#F2D297"},
DiffAdd = {bg = "#31352C"},
DiffChange = {bg = "#2C2F35"},
DiffDelete = {bg = "#352C2D"},
DiffText = {bg = "#2C3235"},
Directory = {fg = "#C1C1C1"},
EndOfBuffer = {fg = "#1E1E1E"},
Error = {fg = "#F2979C", bg = "#352C2D"},
ErrorMsg = {fg = "#F2979C", bold = true, italic = true},
Exception = {fg = "#F2979C"},
Float = {fg = "#F2979C"},
FloatBorder = {fg = "#717171", bg = "#131313"},
FzfLuaBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#EBEBEB", bg = "#131313"},
FoldColumn = {fg = "#484848"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#999999", bg = "#2C2C2C"},
Function = {fg = "#97D8F2"},
FzfLuaBufFlagAlt = {fg = "#97D8F2"},
FzfLuaBufFlagCur = {fg = "#F2979C"},
FzfLuaBufName = {fg = "#CD97F2"},
FzfLuaBufNr = {fg = "#F2D297"},
FzfLuaHeaderBind = {fg = "#F2D297"},
FzfLuaHeaderText = {fg = "#F2979C"},
FzfLuaLiveSym = {fg = "#F2979C"},
FzfLuaPathColNr = {fg = "#97D8F2"},
FzfLuaPathLineNr = {fg = "#CDF297"},
FzfLuaTabMarker = {fg = "#F2D297"},
FzfLuaTabTitle = {fg = "#97B4F2"},
Identifier = {fg = "#97D8F2"},
IncSearch = {fg = "#131313", bg = "#F2D297"},
Include = {fg = "#97D8F2"},
Keyword = {fg = "#CD97F2"},
Label = {fg = "#97D8F2"},
LineNr = {fg = "#5C5C5C"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspCodeLens = {fg = "#5C5C5C"},
LspCodeLensSeparator = {link = "LspCodeLens"},
LspReferenceRead = {bg = "#373737"},
LspReferenceText = {bg = "#373737"},
LspReferenceWrite = {bg = "#373737"},
LspSignatureActiveParameter = {bg = "#2C2C2C", bold = true},
Macro = {fg = "#97B4F2"},
MatchParen = {fg = "#F2D297", bg = "#373737"},
ModeMsg = {fg = "#C1C1C1", bold = true},
MoreMsg = {fg = "#97B4F2"},
MsgArea = {},
MsgSeparator = {},
NeoTreeCursorLine = {fg = "#97B4F2", bg = "#2C2F35"},
NeoTreeNormal = {fg = "#C1C1C1", bg = "#131313"},
NeoTreeRootName = {fg = "#C1C1C1", bold = true},
NeoTreeWinSeparator = {fg = "#131313", bg = "#131313"},
Noise = {fg = "#97D8F2"},
NonText = {fg = "#373737"},
SpecialKey = {link = "NonText"},
NormalFloat = {fg = "#C1C1C1", bg = "#131313"},
FzfLuaNormal = {link = "NormalFloat"},
FzfLuaPreviewNormal = {link = "NormalFloat"},
NormalNC = {fg = "#EBEBEB", bg = "#1E1E1E"},
Number = {fg = "#F2979C"},
NvimTreeCursorLine = {fg = "#97B4F2", bg = "#2C2F35"},
NvimTreeNormal = {fg = "#C1C1C1", bg = "#131313"},
NvimTreeRootFolder = {fg = "#C1C1C1", bold = true},
NvimTreeWinSeparator = {fg = "#131313", bg = "#131313"},
BufferlineOffsetSeparator = {link = "NvimTreeWinSeparator"},
Operator = {fg = "#97D8F2"},
Pmenu = {fg = "#C1C1C1", bg = "#131313"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#131313"},
PmenuSel = {fg = "#97B4F2", bg = "#2C2F35"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#373737"},
PreCondit = {fg = "#97B4F2"},
PreProc = {fg = "#CD97F2"},
Question = {fg = "#97B4F2"},
QuickFixLine = {bg = "#484848"},
Removed = {fg = "#F2979C"},
Repeat = {fg = "#97D8F2"},
Search = {fg = "#131313", bg = "#97B4F2"},
SignColumn = {fg = "#484848"},
CursorLineSign = {link = "SignColumn"},
SnacksDashboardDesc = {fg = "#CD97F2"},
SnacksDashboardFooter = {fg = "#F2D297"},
SnacksDashboardHeader = {fg = "#EBEBEB"},
SnacksDashboardIcon = {fg = "#F2979C"},
SnacksDashboardKey = {fg = "#97B4F2"},
SnacksDashboardSpecial = {fg = "#F2D297"},
SnacksIndentScope = {fg = "#5C5C5C"},
SnacksPickerBufFlags = {fg = "#868686"},
SnacksPickerDir = {fg = "#868686"},
SnacksPickerKeymapRhs = {fg = "#868686"},
SnacksPickerTotals = {fg = "#868686"},
Special = {fg = "#97D8F2"},
SpecialChar = {fg = "#F2979C"},
SpecialComment = {fg = "#999999", italic = true},
SpellBad = {sp = "#F2979C", undercurl = true},
SpellCap = {sp = "#F2D297", undercurl = true},
SpellLocal = {sp = "#97B4F2", undercurl = true},
SpellRare = {sp = "#CDF297", undercurl = true},
Statement = {fg = "#F2979C"},
StatusLine = {fg = "#C1C1C1", bg = "#1E1E1E"},
StatusLineNC = {fg = "#484848", bg = "#1E1E1E"},
StorageClass = {fg = "#B6CAD2"},
String = {fg = "#CDF297"},
Structure = {fg = "#97D8F2"},
Substitute = {fg = "#F2979C", bg = "#484848"},
TabLine = {fg = "#484848", bg = "#131313"},
TabLineFill = {bg = "#131313"},
Tag = {fg = "#F2979C"},
TermCursor = {fg = "#1E1E1E", bg = "#C1C1C1"},
TermCursorNC = {fg = "#1E1E1E", bg = "#999999"},
Title = {fg = "#EBEBEB"},
Todo = {fg = "#97D8F2"},
Type = {fg = "#CD97F2"},
Typedef = {fg = "#F2979C"},
Underlined = {underline = true},
["@markup.underline"] = {link = "Underlined"},
VertSplit = {fg = "#717171"},
Visual = {bg = "#373737"},
VisualNOS = {bg = "#484848"},
WarningMsg = {fg = "#F2D297"},
Whitespace = {fg = "#373737"},
WildMenu = {bg = "#484848"},
WinBar = {fg = "#C1C1C1"},
WinBarNC = {fg = "#5C5C5C"},
Winseparator = {fg = "#717171"},
lCursor = {fg = "#1E1E1E", bg = "#EBEBEB"},
["@attribute"] = {fg = "#CD97F2"},
["@attribute.builtin"] = {fg = "#F2D297"},
["@boolean"] = {fg = "#F2979C"},
["@character"] = {fg = "#EBEBEB"},
["@character.special"] = {fg = "#F2979C"},
["@comment.error"] = {fg = "#F2979C"},
["@comment.note"] = {fg = "#97D8F2"},
["@comment.todo"] = {fg = "#97B4F2"},
["@comment.warning"] = {fg = "#F2D297"},
["@constant"] = {fg = "#EBEBEB"},
["@constant.builtin"] = {fg = "#97D8F2"},
["@constant.macro"] = {fg = "#97B4F2"},
["@constructor"] = {fg = "#CD97F2"},
["@diff.delta"] = {fg = "#97B4F2"},
["@diff.minus"] = {fg = "#F2979C"},
["@diff.plus"] = {fg = "#CDF297"},
["@function"] = {fg = "#97B4F2"},
["@function.builtin"] = {fg = "#97B4F2"},
["@function.call"] = {fg = "#97B4F2"},
["@function.macro"] = {fg = "#97B4F2"},
["@function.method"] = {fg = "#97B4F2"},
["@function.method.call"] = {fg = "#97B4F2"},
["@keyword"] = {fg = "#CD97F2"},
["@keyword.c"] = {fg = "#F2979C"},
["@keyword.conditional"] = {fg = "#97D8F2", italic = true},
["@keyword.conditional.ternary"] = {fg = "#97D8F2"},
["@keyword.coroutine"] = {fg = "#CD97F2"},
["@keyword.cpp"] = {fg = "#F2979C"},
["@keyword.debug"] = {fg = "#F2D297", italic = true},
["@keyword.directive"] = {fg = "#97D8F2", italic = true},
["@keyword.directive.define"] = {fg = "#97D8F2", italic = true},
["@keyword.exception"] = {fg = "#97D8F2", italic = true},
["@keyword.function"] = {fg = "#CD97F2"},
["@keyword.function.rust"] = {fg = "#F2979C"},
["@keyword.import"] = {fg = "#97D8F2"},
["@keyword.modifier"] = {fg = "#CD97F2"},
["@keyword.operator"] = {fg = "#97D8F2"},
["@keyword.repeat"] = {fg = "#97D8F2", italic = true},
["@keyword.return"] = {fg = "#97D8F2", italic = true},
["@keyword.type"] = {fg = "#CD97F2"},
["@label"] = {fg = "#F2D297"},
["@label.markdown"] = {fg = "#CDF297"},
["@lsp.type.class.markdown"] = {fg = "#CDF297"},
["@markup.heading"] = {fg = "#EBEBEB"},
["@markup.heading.1"] = {fg = "#EBEBEB"},
["@markup.heading.1.markdown"] = {fg = "#F2D297"},
["@markup.heading.2"] = {fg = "#EBEBEB"},
["@markup.heading.2.markdown"] = {fg = "#F2D297"},
["@markup.heading.3"] = {fg = "#EBEBEB"},
["@markup.heading.3.markdown"] = {fg = "#F2D297"},
["@markup.heading.4"] = {fg = "#EBEBEB"},
["@markup.heading.4.markdown"] = {fg = "#F2D297"},
["@markup.heading.5"] = {fg = "#EBEBEB"},
["@markup.heading.5.markdown"] = {fg = "#F2D297"},
["@markup.heading.6"] = {fg = "#EBEBEB"},
["@markup.heading.6.markdown"] = {fg = "#F2D297"},
["@markup.heading.markdown"] = {fg = "#F2D297"},
["@markup.italic"] = {fg = "#F2979C", italic = true},
["@markup.link"] = {fg = "#97D8F2"},
["@markup.link.label"] = {fg = "#CDF297"},
["@markup.link.url"] = {fg = "#F2979C"},
["@markup.list"] = {fg = "#97D8F2"},
["@markup.list.checked"] = {fg = "#CDF297"},
["@markup.list.unchecked"] = {fg = "#97B4F2"},
["@markup.math"] = {fg = "#97B4F2"},
["@markup.quote"] = {fg = "#97D8F2", italic = true},
["@markup.raw"] = {fg = "#EBEBEB"},
["@markup.raw.block"] = {fg = "#C1C1C1"},
["@markup.raw.markdown_inline"] = {fg = "#CDF297"},
["@markup.strikethrough"] = {fg = "#EBEBEB", strikethrough = true},
["@markup.strong"] = {fg = "#F2979C", bold = true},
["@module"] = {fg = "#F2D297"},
["@module.python"] = {fg = "#EBEBEB"},
["@number"] = {fg = "#F2979C"},
["@number.float"] = {fg = "#F2979C"},
["@operator"] = {fg = "#97D8F2"},
["@property"] = {fg = "#B6CAD2"},
["@punctuation.bracket"] = {fg = "#97D8F2"},
["@punctuation.delimiter"] = {fg = "#97D8F2"},
["@punctuation.special"] = {fg = "#97D8F2"},
["@string"] = {fg = "#CDF297"},
["@string.escape"] = {fg = "#EBEBEB"},
["@string.regexp"] = {fg = "#CDF297"},
["@string.special.symbol"] = {fg = "#97D8F2"},
["@string.special.url"] = {underline = true},
["@tag"] = {fg = "#F2979C"},
["@tag.attribute"] = {fg = "#CD97F2"},
["@tag.delimiter"] = {fg = "#97D8F2"},
["@type"] = {fg = "#F2D297"},
["@type.builtin"] = {fg = "#F2D297"},
["@type.builtin.c"] = {fg = "#CD97F2"},
["@type.builtin.cpp"] = {fg = "#CD97F2"},
["@type.definition"] = {fg = "#F2D297"},
["@variable"] = {fg = "#EBEBEB"},
["@variable.builtin"] = {fg = "#97D8F2"},
["@variable.member"] = {fg = "#EBEBEB"},
["@variable.parameter"] = {fg = "#EBEBEB", italic = true},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='neutr'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
